#! /bin/sh
#
# If the ./configure script is missing, you can run this script to create it
#

if ! test -e config; then
 mkdir config
fi

if ! test -e config/ltmain.sh; then
 cp /usr/share/libtool/ltmain.sh config
fi

aclocal \
&& automake --gnu --add-missing \
&& autoconf
rm -rf autom4te.cache
