#  -*- mode: makefile -*-
# 
#  Copyright (c) 2001-2002 Tweak Films.
#  All rights reserved. 
# 

PROJECT    = GelGto
TYPE       = LIBRARY

CXXFILES   = DataBase Object Plugin OnOffList Reader Set Subd NURBS Poly Strand
IPATH      = $(ENTROPYHOME)/include \
             /vol/apps/prman/include \
             /usr/local/prman-11.1/include \
             $(GELATOHOME)/include
LIBS       = 
PUBLIC     = 

include $(SRC_ROOT)/build/Makefile.master
